name: CI/CD Pipeline Auto

on:
  push:
    branches: [main]

jobs:
  laravel:
    name: 🧪 Laravel Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Run Tests
        run: php artisan test


  nextjs:
    name: 🌐 Cypress + Build Next
    runs-on: ubuntu-latest
    needs: laravel

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Run Cypress Tests
        working-directory: frontend
        run: npx cypress run


  deploy:
    name: 🚀 Auto Deploy to FTP
    runs-on: ubuntu-latest
    needs: [laravel, nextjs]

    steps:
      - uses: actions/checkout@v3

      - name: Upload to FTP (via secrets)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.tpecloud.ci
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/
          local-dir: ./deploy/
