name: 🚀 Deploy Laravel Backend Only

on:
  push:
    branches: [main]  # ou remplace par la branche de travail

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy Laravel Backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./inscription-formation-api/ # indiquer à GitHub Actions d’envoyer uniquement le contenu du dossier inscription-formation-api/ via FTP.
