name: 🚀 Deploy Laravel Backend Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Étape 2 : Installer PHP pour composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Étape 3 : Installer les dépendances Laravel
      - name: Install Dependencies
        working-directory: ./inscription-formation-api
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Étape 4 : Déploiement FTP
      - name: Deploy Laravel Backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
          local-dir: ./inscription-formation-api/
