name: 🚀 Deploy Laravel Backend API Only

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy Laravel API
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Récupérer le code
        uses: actions/checkout@v4

      - name: 🧰 Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: 📦 Installer les dépendances Laravel
        working-directory: ./inscription-formation-api
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 📂 Déployer le backend Laravel dans /api
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }} # /api/
          local-dir: ./inscription-formation-api/
          exclude: |
            .env
            .git*
            node_modules/**
            storage/logs/**
            tests/**
            .github/**

      - name: 🧾 Déployer le contenu de public/ à la racine du sous-domaine
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}/../
          local-dir: ./inscription-formation-api/public/
          exclude: |
            .git*
            .github/**
